### ISSUE TITLE
Move @license under @copyright

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/boilerplate#10]
A very pedantic suggestion but one which has some logic in my mind at least:

Licensing is the right to use something, and for code here, comes because the author who wrote it has natural copyright. To me, it makes sense to define the name of the package, who wrote it, who owns the copyright _and then_ under what license (if any), the code is made available:

```
* @package   Gamajo\CoreContributions
 * @author    Gary Jones
 * @copyright 2016 Gary Jones, Gamajo
 * @license   MIT
```

**Comment by schlessera** [comment]
Valid point, but what about the fact that copyright is included as the very last item almost everywhere it is included (probably to "encompass all that was mentioned before")?

**Comment by GaryJones** [comment]
> what about the fact that copyright is included as the very last item almost everywhere it is included (probably to "encompass all that was mentioned before")?

I've not seen that point made explicit like that, but...you don't own the copyright to any SPDX-identifiable license.

**Comment by schlessera** [comment]
Huh? I'm not sure I understand...

**Comment by schlessera** [comment]
Launched a poll: https://twitter.com/schlessera/status/781787052681654273

**Comment by GaryJones** [comment]
https://github.com/WordPress/WordPress/blob/master/license.txt

States the copyright at the top, and then the license under which that copyrighted code is made available.

Same for:
https://github.com/jquery/jquery/blob/master/LICENSE.txt
https://github.com/guzzle/guzzle/blob/master/LICENSE
https://github.com/sebastianbergmann/phpunit/blob/5.5/LICENSE
https://github.com/rdlowrey/auryn/blob/master/LICENSE (any MIT License)
https://github.com/phpDocumentor/phpDocumentor2/blob/develop/src/Application/Application.php
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/actions.php

**Comment by schlessera** [comment]
Well, that is the license file. When you look at the readme file (https://github.com/WordPress/WordPress/blob/master/readme.html), which should be considered the entry point, you can see that it is referenced at the bottom.

So, the flow of reading is:
1. yada-yada Readme
2. License ->
3. -> Copyright

**Comment by schlessera** [comment]
And btw, all the license files you linked to first state what license you are currently reading (the title), and then show the copyright.
