### ISSUE TITLE
Add explicit question for Copyright name

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/boilerplate#11]
My package vendor name is `Gamajo`, but my company name is Gamajo Tech. The wording of the question doesn't make it clear that it should be re-used.

Similarly, the copyright currently uses `John Smith, Company Name`, but someone might be writing code where copyright is automatically transfered to their company only, and not them.

Asking an explicit question such as "Name of the copyright owner entity?" would allow this to be fine-tuned in both situations. It can default to whatever is convenient for you.

**Comment by schlessera** [comment]
Yes, adding such stuff that provides a pre-built default should be no problem.
