### ISSUE TITLE
Add support for creating WordPress plugins

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/boilerplate#13]
Having a question such as "Is this a WordPress plugin?" would allow the boilerplate to add in several amendments, such as the bootstrap file (`my-test-plgin.php`), amended test files (extending `WP_Unit_TestCase`, tests/bootstrap.php), WP Code Standards package requirement and setup, and so on.

For me (and I suspect you as well), this would make this boilerplate package extra useful as a starting point for both standalone packages and creating new WordPress plugins.

**Comment by schlessera** [comment]
Ping @schlessera ! :)

**Comment by schlessera** [comment]
@GaryJones Would like to make progress with this in the near future, would love your feedback on this list of decision points that might shape the resulting plugin:

1. [Theme,] normal plugin or must-use plugin (for Composer type)
2. Uses Configuration
3. Uses external assets (dependencies)
4. Has option(s)
5. Has settings page(s)
6. Has shortcode(s)
7. Has widget(s)
8. Include unit tests
9. Include integration tests

I think these should be pretty common for most plugins. Are there other common elements I've missed?

**Comment by GaryJones** [comment]
Questions to include / adjust any of the following:

* [`.editorconfig`](https://github.com/GaryJones/plugin-boilerplate/blob/31742e9c751df7362a88b7342dea392a3f89b2d1/.editorconfig)
* [`phpcs.xml`](https://github.com/GaryJones/plugin-boilerplate/blob/31742e9c751df7362a88b7342dea392a3f89b2d1/phpcs.xml)
* [`.travis.yml`](https://github.com/GaryJones/plugin-boilerplate/blob/31742e9c751df7362a88b7342dea392a3f89b2d1/.travis.yml)

They all have some reference to WordPress.

As an aside, some other general inclusions / questions:

* Will be stored on GitHub? (for creation of `.github/[CONTRIBUTING|ISSUE_TEMPLATE|PULL_REQUEST_TEMPLATE].md`)
* Has views? (for creation of `views/`)
* Minimum required version of PHP? (can add to `composer.json`, add strict types declaration to `.php` if PHP 7+, use long array syntax if < 5.4 etc.)
* Has log files? (for creation of `logs/` and add to `.gitignore`)
