### ISSUE TITLE
Support GPL-2.0 License

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/boilerplate#8]
Along with `MIT` for general packages, WordPress plugins should be `GPL-2.0+`, so it would be great to allow a choice of license used (the file, and reference in composer.json, and in file headers).

If the desired license is exactly `GPL-2.0` or `GPL-2.0+`, then the GPL v2 should be in `LICENSE`.

**Comment by schlessera** [comment]
I wanted to add a way to select one of several licenses.

However, your point about WordPress plugins is not true, MIT is considered a valid equivalent by the plugin review team.

**Comment by GaryJones** [comment]
> However, your point about WordPress plugins is not true, MIT is considered a valid equivalent by the plugin review team.

Fact-checked, and agreed :-)
